import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/redux/Provider";
import FetctInitialData from "./FetctInitialData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[1500px]  mx-auto ">
        <ReduxProvider>
          <FetctInitialData>
            <Header />
            {children}
            <Footer />
          </FetctInitialData>
        </ReduxProvider>
      </body>
    </html>
  );
}
