
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/redux/Provider";
import FetctInitialData from "./FetctInitialData";
import { SessionProvider } from "next-auth/react";
import BasicLayout from "./rootLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang="en">
      <body className="max-w-[1500px]  mx-auto ">
      <BasicLayout children={children} params={params} />
      </body>
    </html>
  );
}
